name: E2E Login (Cypress)

on:
  push:
    branches: [ main, master, develop, feature/** ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Run Cypress tests (headless)
        run: npm run cy:run

      - name: Generate Mochawesome HTML report
        run: npm run report

      - name: Upload Mochawesome HTML report
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: reports/html
          if-no-files-found: error

      - name: Upload Cypress screenshots (on failures)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
